version: '3.8'

services:
  yaml-formatter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - ollama
    networks:
      - yaml-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - yaml-network

volumes:
  ollama-data:

networks:
  yaml-network:
    driver: bridge
